Repository Conflux-Chain/helios, pull requests merged in 2021-08, with the labels that each got.

#69 ci: auto-comment-on-release
  .github/scripts/commentPRDebugRelease.js
  .github/scripts/deleteOldDebugRelease.js
  .github/scripts/getDebugRelease.js
  .github/workflows/comment-on-release.yaml
  .github/workflows/debug-release.yaml
  .github/workflows/deploy-doc.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
Labels: ci

#71 build: replace babel-jest, upgrade jest
  .yarn/versions/eb061483.yml
  jest.config.js
  package.json
  packages/jest-helper/README.md
  packages/jest-helper/index.js
  packages/jest-helper/package.json
  packages/jest-helper/setup-after-env.js
  packages/json-rpc-error/index.test.js
  packages/ui/Alert/index.js
  packages/ui/Button/index.js
  packages/ui/Input/index.js
  packages/ui/Link/index.js
  packages/ui/Menu/MenuItem.js
  packages/ui/Modal/index.js
  packages/ui/Tag/index.js
  packages/ui/Toast/index.js
  scripts/integration-test.js
  scripts/jest-transformers.js
  scripts/snowpack.base.config.js
  yarn.lock
Labels: tests

#72 feat: shorten-address
  .yarn/versions/ceca1688.yml
  packages/ui/Alert/index.js
  packages/ui/Input/index.js
  packages/ui/Link/index.js
  packages/ui/Tag/index.js
  packages/ui/data-format/README.md
  packages/ui/data-format/index.js
  packages/ui/data-format/index.test.js
  packages/ui/data-format/package.json
  packages/ui/shorten-address/README.md
  packages/ui/shorten-address/index.js
  packages/ui/shorten-address/index.test.js
  packages/ui/shorten-address/package.json
  yarn.lock
Labels: enhancement, tests

#81 feat: add useStore
  .github/release-drafter.yml
  .github/workflows/debug-release.yaml
  .github/workflows/pre-release.yaml
  .yarn/versions/6fb2fbc4.yml
  packages/popup/package.json
  packages/popup/src/App.js
  packages/popup/src/index.js
  packages/popup/src/store/befores.js
  packages/popup/src/store/index.js
  packages/popup/src/store/init-store.js
  packages/popup/src/store/rpc-config.js
  packages/popup/src/store/useStore.js
  packages/ui/useRPC/index.js
  packages/ui/useRPC/setup-ext-provider.js
  packages/ui/useRPC/setup-provider.js
  yarn.lock
Labels: enhancement, patch

#86 fix(useStore): cache accessing with ref
  .github/workflows/debug-release.yaml
  .yarn/versions/377503a0.yml
  packages/popup/package.json
  packages/popup/src/App.js
  packages/popup/src/store/useStore.js
  packages/ui/useRPC/index.js
  packages/ui/useRPC/setup-ext-provider.js
  yarn.lock
Labels: fix
