Repository Conflux-Chain/helios, pull requests merged in 2021-12, with the labels that each got.

#265 feat: tx list
  .github/scripts/assert-fullnode-error-message-check.mjs
  .yarn/versions/f9938e00.yml
  packages/background/package.json
  packages/background/src/db-schema.js
  packages/background/src/index.js
  packages/background/src/init-db.js
  packages/background/src/rpc-engine-opts.js
  packages/db/src/main/cfxjs/db/core.cljs
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/rpcs/cfx_sendTransaction/doc.js
  packages/rpcs/cfx_sendTransaction/index.js
  packages/rpcs/wallet_cleanupTx/README.md
  packages/rpcs/wallet_cleanupTx/doc.js
  packages/rpcs/wallet_cleanupTx/index.js
  packages/rpcs/wallet_cleanupTx/package.json
  packages/rpcs/wallet_enrichConfluxTx/README.md
  packages/rpcs/wallet_enrichConfluxTx/doc.js
  packages/rpcs/wallet_enrichConfluxTx/index.js
  packages/rpcs/wallet_enrichConfluxTx/package.json
  packages/rpcs/wallet_enrichConfluxTxs/README.md
  packages/rpcs/wallet_enrichConfluxTxs/doc.js
  packages/rpcs/wallet_enrichConfluxTxs/index.js
  packages/rpcs/wallet_enrichConfluxTxs/package.json
  packages/rpcs/wallet_generateAddress/doc.js
  packages/rpcs/wallet_generateAddress/index.js
  packages/rpcs/wallet_generateMnemonic/doc.js
  packages/rpcs/wallet_generateMnemonic/index.js
  packages/rpcs/wallet_generatePrivateKey/doc.js
  packages/rpcs/wallet_generatePrivateKey/index.js
  packages/rpcs/wallet_handleUnfinishedCFXTx/doc.js
  packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
  packages/rpcs/wallet_handleUnfinishedTxs/doc.js
  packages/rpcs/wallet_refetchBalance/index.js
  packages/rpcs/wallet_updateTokenList/index.js
  packages/transducers/index.js
  packages/ui/provider-api/index.js
  yarn.lock
Labels: feature

#267 fix: PORTAL-1561
  .yarn/versions/460db580.yml
  packages/popup/src/components/HomeNav.js
  packages/popup/src/components/TokenItem.js
  packages/popup/src/components/TokenList.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/Home/components/HomeTokenList.js
  packages/popup/src/pages/Home/index.js
Labels: fix

#270 feat: optimize tx query, update manifest.json
  .github/scripts/assert-fullnode-error-message-check.mjs
  .github/scripts/getPRRelease.js
  .github/workflows/debug-release.yaml
  .yarn/versions/23e4d918.yml
  packages/browser-extension/manifest.json.mustache
  packages/db/src/main/cfxjs/db/queries.cljs
  scripts/before_all.js
Labels: feature

#272 feat: count only for tx query
  .yarn/versions/7672a2f0.yml
  packages/db/src/main/cfxjs/db/queries.cljs
Labels: feature

#274 fix: minor fixes
  .yarn/versions/936eabf0.yml
  packages/background/src/db-schema.js
  packages/rpc-engine/src/error.js
  scripts/before_all.js
Labels: fix

#277 fix: better err msg and doc for sign typed data
  .yarn/versions/6ba7c838.yml
  packages/rpcs/cfx_signTypedData_v4/doc.js
  packages/rpcs/cfx_signTypedData_v4/index.js
Labels: fix

#276 fix: PORTAL-1579
  .yarn/versions/125eb1b1.yml
  packages/popup/src/pages/EditGasFee/index.js
Labels: fix

#282 fix: dapp edit gas bug
  .yarn/versions/536e0a8d.yml
  packages/popup/src/components/GasFee.js
  packages/popup/src/pages/ConfirmTransaction/index.js
Labels: fix

#279 feat: add tx history
  .yarn/versions/821da68c.yml
  packages/popup/package.json
  packages/popup/src/App.js
  packages/popup/src/components/CopyButton.js
  packages/popup/src/components/CustomTag.js
  packages/popup/src/constants/index.js
  packages/popup/src/constants/route.js
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/History/components/HistoryItem.js
  packages/popup/src/pages/History/index.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/PendingQueue.js
  packages/popup/src/pages/Home/components/index.js
  packages/popup/src/pages/Home/index.js
  packages/popup/src/utils/index.js
  packages/ui/icons/ReloadOutlined.js
  packages/ui/icons/SendOutlined.js
  packages/ui/icons/index.js
  yarn.lock
Labels: feature

#285 fix: fix some bugs and some style check
  .yarn/versions/1c6e4823.yml
  packages/popup/src/constants/index.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/EditGasFee/index.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/SelectCreateType/index.js
Labels: fix

#287 feat: add pub key filter
  .yarn/versions/0bdae1b1.yml
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/History/index.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/webextension/popup.js
Labels: feature

#280 feat: handle pivot chain switch for unfinished tx
  .github/scripts/assert-fullnode-error-message-check.mjs
  .yarn/versions/7179d410.yml
  packages/background/src/db-schema.js
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
  packages/signature/index.js
  packages/ui/provider-api/index.js
Labels: feature

#297 fix: typo casuing wrong unlock page in prod
  .yarn/versions/1faef8a9.yml
  packages/rpcs/wallet_requestUnlockUI/index.js
Labels: fix

#291 fix: fix logic bugs
  .yarn/versions/46d12a2a.yml
  packages/popup/src/components/CopyButton.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/ConfirmAddSuggestedToken/index.js
  packages/popup/src/pages/ConnectSite/index.js
  packages/popup/src/pages/History/components/HistoryItem.js
  packages/popup/src/pages/History/index.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/RequestSignature/index.js
Labels: fix

#300 fix: PORTAL-1685, add no tx history alert
  .yarn/versions/434c0162.yml
  packages/popup/package.json
  packages/popup/src/pages/SendTransaction/index.js
  packages/tx-history-checker/README.md
  packages/tx-history-checker/index.js
  packages/tx-history-checker/package.json
  yarn.lock
Labels: fix

#299 fix: tx workflow
  .yarn/versions/a7a784ea.yml
  packages/background/src/db-schema.js
  packages/background/src/index.js
  packages/conflux-tx-error/index.js
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/popup/src/components/HomeNav.js
  packages/rpcs/cfx_sendTransaction/index.js
  packages/rpcs/wallet_addConfluxChain/doc.js
  packages/rpcs/wallet_addEthereumChain/doc.js
  packages/rpcs/wallet_addEthereumChain/index.js
  packages/rpcs/wallet_enrichConfluxTx/index.js
  packages/rpcs/wallet_getPendingAuthRequest/index.js
  packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
  packages/rpcs/wallet_watchAsset/index.js
Labels: fix

#294 feat: fix some bugs
  .yarn/versions/8654aaba.yml
  packages/contract-method-name/cfx-name.test.js
  packages/contract-method-name/eth-name.test.js
  packages/estimate-tx/index.js
  packages/popup/package.json
  packages/popup/src/components/DappFooter.js
  packages/popup/src/components/GasFee.js
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/components/SlideCard.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/index.css
  packages/popup/src/pages/ConfirmAddSuggestedToken/index.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/ConnectSite/index.js
  packages/popup/src/pages/EditGasFee/index.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/Home/components/CurrentAccount.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/Home/components/NetworkList.js
  packages/popup/src/pages/Home/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/RequestSignature/index.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/ui/components/Alert/__snapshots__/index.test.js.snap
  packages/ui/components/Alert/index.js
  packages/ui/components/Menu/package.json
  packages/ui/components/Message/index.js
  packages/ui/components/Message/index.test.js
  packages/ui/components/Message/package.json
  packages/ui/components/Notification/index.js
  packages/ui/components/Notification/index.test.js
  packages/ui/components/Notification/package.json
  yarn.lock
Labels: tests, feature

#308 fix: fix PORTAL-1690
  .yarn/versions/a7ac5152.yml
  packages/popup/src/pages/Home/components/useAuthorizedAccountIdIcon.js
Labels: fix

#311 fix: fixed overlap and scroll issue
  .yarn/versions/49a693da.yml
  packages/popup/src/pages/Home/components/HomeTokenList.js
  packages/webextension/popup.js
Labels: fix

#310 feat: db migration, frontend refactor
  .yarn/versions/a77ed31e.yml
  packages/background/src/db-schema.js
  packages/background/src/index.integration.test.js
  packages/background/src/rpc-engine-opts.js
  packages/db/src/db.test.js
  packages/db/src/main/cfxjs/db/core.cljs
  packages/db/src/main/cfxjs/db/migrate.cljs
  packages/db/src/main/cfxjs/db/migrations/core.cljs
  packages/db/src/main/cfxjs/db/migrations/m1.cljs
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/doc-ui/useSpec/index.js
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/components/TokenItem.js
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/index.js
  packages/popup/src/pages/AccountManagement/index.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
  packages/popup/src/pages/ConfirmTransaction/components/TransactionResult.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/History/components/HistoryItem.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/Home/components/CurrentAccount.js
  packages/popup/src/pages/Home/components/CurrentAccountNetworkLabel.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/Home/components/CurrentNetwork.js
  packages/popup/src/pages/Home/components/HomeTokenList.js
  packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/rpcs/wallet_addNetwork/index.js
  packages/rpcs/wallet_getBlockchainExplorerUrl/index.js
  packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
Labels: tests, feature

#313 feat: add hardware wallet rpc methods
  .yarn/versions/265578bf.yml
  packages/background/package.json
  packages/background/src/db-schema.js
  packages/background/src/rpc-engine-opts.js
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/rpcs/wallet_addVault/index.js
  packages/rpcs/wallet_getAccountGroup/index.js
  packages/rpcs/wallet_getImportHardwareWalletInfo/README.md
  packages/rpcs/wallet_getImportHardwareWalletInfo/doc.js
  packages/rpcs/wallet_getImportHardwareWalletInfo/index.js
  packages/rpcs/wallet_getImportHardwareWalletInfo/package.json
  packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/README.md
  packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/doc.js
  packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
  packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/package.json
  yarn.lock
Labels: tests, feature

#318 feat: add device to vault
  .yarn/versions/3022d7c1.yml
  package.json
  packages/background/src/db-schema.js
  packages/db/src/main/cfxjs/db/core.cljs
  packages/db/src/main/cfxjs/db/migrate.cljs
  packages/db/src/main/cfxjs/db/migrations/core.cljs
  packages/db/src/main/cfxjs/db/migrations/m2.cljs
  packages/db/src/main/cfxjs/db/preloads.cljs
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/rpcs/wallet_addVault/index.js
  packages/rpcs/wallet_getImportHardwareWalletInfo/index.js
  packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
  shadow-cljs.edn
  yarn.lock
Labels: feature

#320 feat: ledger package
  .yarn/versions/e1a9becc.yml
  packages/ledger/README.md
  packages/ledger/conflux.js
  packages/ledger/const.js
  packages/ledger/index.js
  packages/ledger/package.json
  packages/popup/package.json
  packages/popup/src/hooks/useLedger.js
  yarn.lock
Labels: feature

#324 feat: add getDeviceInfo api
  .yarn/versions/6ef39575.yml
  packages/ledger/conflux.js
  packages/ledger/const.js
Labels: feature

#326 feat: add useImportHW hook
  .yarn/versions/7525a40b.yml
  package.json
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/doc-ui/rpc-parameter/package.json
  packages/doc-ui/try-rpc/package.json
  packages/doc-ui/useRPC/package.json
  packages/doc-ui/useSpec/package.json
  packages/popup/package.json
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/utils/index.js
  packages/rpcs/wallet_getImportHardwareWalletInfo/index.js
  packages/rpcs/wallet_userApprovedAuthRequest/index.js
  packages/rpcs/wallet_userRejectedAuthRequest/index.js
  packages/rpcs/wallet_watchAsset/index.js
  packages/rpcs/wallet_zeroAccountGroup/index.js
  packages/test-helpers/package.json
  packages/ui/useRPC/package.json
  yarn.lock
Labels: feature

#328 fix: fix bugs
  .yarn/versions/acebc4d2.yml
  packages/popup/package.json
  packages/popup/src/components/DappFooter.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/EditGasFee/index.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/ui/icons/FileOutlined.js
  packages/ui/icons/index.js
  yarn.lock
Labels: fix

#331 fix: fix some bugs and add ledger ui check
  .yarn/versions/37875340.yml
  packages/popup/src/App.js
  packages/popup/src/components/HwAlert.js
  packages/popup/src/components/index.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/ui/components/Alert/__snapshots__/index.test.js.snap
  packages/ui/components/Alert/index.js
Labels: fix

#337 fix: fix bugs and add comment to debbug
  .yarn/versions/5d2024f3.yml
  packages/popup/src/hooks/index.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/SendTransaction/index.js
Labels: fix

#341 fix(ledger): can not claim interface
  .yarn/versions/e0c94804.yml
  packages/popup/src/constants/index.js
  packages/popup/src/hooks/useLedger.js
  packages/popup/src/pages/ConfirmTransaction/index.js
Labels: fix

#340 fix: delete useless token when tokenlist updated
  .yarn/versions/9f5bf4d0.yml
  packages/db/src/main/cfxjs/db/queries.cljs
  shadow-cljs.edn
Labels: fix

#336 feat: add router level transition
  .yarn/versions/319c89ec.yml
  packages/popup/package.json
  packages/popup/src/App.css
  packages/popup/src/App.js
  yarn.lock
Labels: feature

#345 fix: PORTAL-1822 and add hw tx modal
  .yarn/versions/91505f65.yml
  packages/popup/src/constants/index.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
  packages/popup/src/pages/ConfirmTransaction/components/index.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/ui/components/Modal/index.js
Labels: fix

#346 fix: db fix
  .yarn/versions/f7ca5701.yml
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/rpcs/wallet_lock/index.js
  packages/rpcs/wallet_lock/index.test.js
  packages/rpcs/wallet_setCurrentAccount/index.js
  packages/rpcs/wallet_unlock/index.js
  packages/rpcs/wallet_unlock/index.test.js
Labels: tests, fix

#349 fix: fix bugs
  .yarn/versions/7a0199ba.yml
  packages/popup/src/components/SlideCard.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/History/components/HistoryItem.js
  packages/popup/src/pages/History/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/Unlock/index.js
  packages/popup/src/utils/index.js
  scripts/tailwind.config.js
Labels: fix

#352 fix: no need to init confluxJS.provider after connect
  .yarn/versions/7179299f.yml
  packages/ui/provider-api/index.js
Labels: fix

#354 fix: bugs
  .yarn/versions/9307cbdf.yml
  packages/conflux-tx-error/index.js
  packages/rpcs/cfx_sendTransaction/index.js
  packages/ui/provider-api/index.js
Labels: fix

#356 fix: several bugs, check body for detail
  .github/scripts/assert-fullnode-error-message-check.mjs
  .github/scripts/check-conflux-rust-error-messages
  .github/workflows/check-conflux-fullnode-error-message.yaml
  .yarn/versions/79baed41.yml
  packages/background/src/index.integration.test.js
  packages/rpcs/wallet_lock/index.js
  packages/rpcs/wallet_requestPermissions/index.js
  packages/rpcs/wallet_unlock/index.js
Labels: ci, tests, fix

#360 fix: forget custom token address in addToken
  .yarn/versions/948c3cdd.yml
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
Labels: fix

#358 feat: add useLoading hooks
  .yarn/versions/0f720d7a.yml
  packages/popup/src/App.css
  packages/popup/src/App.js
  packages/popup/src/hooks/useLoading/PageLoading.js
  packages/popup/src/hooks/useLoading/index.css
  packages/popup/src/hooks/useLoading/index.js
Labels: feature

#357 fix: fix bugs
  .yarn/versions/153d64b1.yml
  packages/popup/src/App.js
  packages/popup/src/components/IdentityPanel.js
  packages/popup/src/components/ProtectedRoute.js
  packages/popup/src/components/SlideCard.js
  packages/popup/src/constants/index.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/AccountManagement/index.js
  packages/popup/src/pages/ConfirmAddSuggestedToken/index.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/ConnectHardwareWallet/index.js
  packages/popup/src/pages/ConnectSite/index.js
  packages/popup/src/pages/CreateSeed/BackupSeed.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/DappAddNetwork/index.js
  packages/popup/src/pages/DappSwitchNetwork/index.js
  packages/popup/src/pages/EditGasFee/index.js
  packages/popup/src/pages/EditPermission/index.js
  packages/popup/src/pages/Error/index.js
  packages/popup/src/pages/ExportPrivateKey/index.js
  packages/popup/src/pages/ExportSeed/index.js
  packages/popup/src/pages/HardwareGuard/index.js
  packages/popup/src/pages/History/index.js
  packages/popup/src/pages/Home/index.js
  packages/popup/src/pages/ImportHwAccount/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/RequestSignature/index.js
  packages/popup/src/pages/SelectCreateType/index.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/popup/src/pages/SetPassword/index.js
  packages/popup/src/pages/Unlock/index.js
  packages/popup/src/pages/ViewData/index.js
  packages/popup/src/pages/Welcome/index.js
  packages/popup/src/utils/index.js
  scripts/tailwind.config.js
Labels: fix

#364 fix: PORTAL-1816 POTAL-1856
  .yarn/versions/6c486f02.yml
  packages/popup/src/components/HwAlert.js
  packages/popup/src/pages/ConfirmTransaction/index.js
Labels: fix

#367 fix: fix bugs
  .yarn/versions/ca17830e.yml
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/ViewData/index.js
Labels: fix

#362 fix: confluxJS.provider
  .env.production
  .github/release-drafter-pre.yml
  .github/release-drafter-prod.yml
  .github/release-drafter.yml
  .github/workflows/debug-release.yaml
  .github/workflows/pre-release.yaml
  .yarn/versions/29e44676.yml
  packages/background/package.json
  packages/background/src/db-schema.js
  packages/background/src/index.js
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/popup/package.json
  packages/popup/src/index.js
  packages/rpc-engine/index.js
  packages/rpc-engine/middlewares/call-rpc.js
  packages/rpc-engine/src/error.js
  packages/rpcs/cfx_sendTransaction/index.js
  packages/rpcs/cfx_signTransaction/index.js
  packages/rpcs/wallet_importMnemonic/index.js
  packages/rpcs/wallet_zeroAccountGroup/index.js
  packages/sentry/README.md
  packages/sentry/computeDefaultOptions.js
  packages/sentry/index.js
  packages/sentry/package.json
  packages/ui/provider-api/index.js
  packages/webextension/index.js
  packages/webextension/runtime.js
  yarn.lock
Labels: fix

#369 feat: add Spin Loading in useLoading hook
  .yarn/versions/cc6b3184.yml
  packages/popup/src/App.css
  packages/popup/src/App.js
  packages/popup/src/hooks/useLoading/createPageLoading.css
  packages/popup/src/hooks/useLoading/createPageLoading.js
  packages/popup/src/hooks/useLoading/createSpinLoading.css
  packages/popup/src/hooks/useLoading/createSpinLoading.js
  packages/popup/src/hooks/useLoading/createTextLoading.js
  packages/popup/src/hooks/useLoading/index.css
  packages/popup/src/hooks/useLoading/index.js
  packages/popup/src/index.css
  scripts/tailwind.config.js
Labels: feature

#373 feat: use gas station for mainnet
  .yarn/versions/d7cad271.yml
  packages/rpcs/cfx_gasPrice/index.js
Labels: feature

#376 fix: bug
  .yarn/versions/84867475.yml
  packages/popup/src/pages/ConnectHardwareWallet/index.js
Labels: fix

#379 fix: fix bugs
  .yarn/versions/d6a0a265.yml
  packages/browser-extension/images/key.svg
  packages/popup/src/App.js
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/hooks/index.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/AccountManagement/index.js
  packages/popup/src/pages/ConnectHardwareWallet/index.js
  packages/popup/src/pages/ImportHwAccount/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/utils/index.js
Labels: fix

#378 fix: bugs
  .env.development
  .env.production
  .yarn/versions/e86710be.yml
  packages/browser-extension/manifest.json.mustache
  packages/popup/src/hooks/index.js
  packages/popup/src/index.js
  packages/rpc-engine/middlewares/call-rpc.js
  packages/rpc-engine/src/error.js
  packages/rpcs/wallet_addPendingUserAuthRequest/index.js
  packages/sentry/computeDefaultOptions.js
  packages/signature/index.js
  packages/ui/provider-api/index.js
  scripts/before_all.js
  scripts/dev.js
Labels: fix

#380 feat: add features
  .yarn/versions/b1b78c22.yml
  packages/background/public/index.html
  packages/browser-extension/images/bg-homepage.svg
  packages/browser-extension/images/bg.svg
  packages/browser-extension/images/icon-128.png
  packages/browser-extension/images/icon-16.png
  packages/browser-extension/images/icon-19.png
  packages/browser-extension/images/icon-32.png
  packages/browser-extension/images/icon-38.png
  packages/browser-extension/images/icon-512.png
  packages/browser-extension/images/icon-64.png
  packages/browser-extension/images/logo-horizontal.svg
  packages/browser-extension/images/logo-plugin.svg
  packages/browser-extension/images/logo-vertical.svg
  packages/index.html
  packages/popup/public/index.html.mustache
  packages/popup/src/components/HomeNav.js
  packages/popup/src/components/HomeTitle.js
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/hooks/index.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/AccountManagement/index.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/SetPassword/index.js
  packages/popup/src/pages/Unlock/index.js
  packages/popup/src/pages/Welcome/index.js
  packages/webextension/popup.js
  scripts/tailwind.config.js
Labels: feature

#385 fix: fixed typo issue of invaildConfirmPassword
  .yarn/versions/d15af05d.yml
  packages/popup/src/locales/en.js
Labels: fix

#388 fix: guard only inpage method in call-rpc
  .yarn/versions/cfbce5c8.yml
  packages/rpc-engine/middlewares/call-rpc.js
Labels: fix

#387 fix: fix wrong syntax
  .yarn/versions/ee3d8cbf.yml
  packages/popup/src/utils/index.js
Labels: fix

#391 fix: wrong version format
  scripts/before_all.js
Labels: fix

#383 fix: fix bugs
  .yarn/versions/b3fc5e44.yml
  packages/popup/package.json
  packages/popup/src/components/DappProgressHeader.js
  packages/popup/src/components/DisplayBalance.js
  packages/popup/src/hooks/index.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
  packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/DappAddNetwork/index.js
  packages/popup/src/pages/DappSwitchNetwork/index.js
  packages/popup/src/pages/History/components/HistoryItem.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/Home/components/CurrentNetwork.js
  packages/ui/components/Dropdown/__snapshots__/index.test.js.snap
  packages/ui/components/Dropdown/index.js
  packages/ui/components/Dropdown/index.test.js
  packages/ui/components/Popover/__snapshots__/index.test.js.snap
  packages/ui/components/Popover/index.test.js
  packages/ui/components/Tooltip/__snapshots__/index.test.js.snap
  packages/ui/components/Tooltip/index.js
  packages/ui/components/Tooltip/index.test.js
  packages/ui/data-format/index.js
  yarn.lock
Labels: tests, fix

#393 fix: accountsChanged event when expanding auth
  .yarn/versions/f2933cb3.yml
  packages/rpcs/wallet_requestPermissions/index.js
Labels: fix

#394 fix: optimize validateAppPermissions error message
  .yarn/versions/0e334e6d.yml
  packages/rpcs/wallet_validateAppPermissions/index.js
Labels: fix

#397 fix: compare nonce with goog.math.Long
  .yarn/versions/1a0732fa.yml
  packages/db/src/main/cfxjs/db/queries.cljs
Labels: fix

#398 fix: change style
  .yarn/versions/ee3d8cbf.yml
  packages/popup/src/pages/AccountManagement/index.js
  packages/popup/src/pages/Home/index.js
  packages/popup/src/pages/ImportHwAccount/index.js
  packages/popup/src/pages/Unlock/index.js
Labels: fix

#400 fix: bugs
  .yarn/versions/cbb6a40a.yml
  packages/popup/src/hooks/index.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/EditPermission/index.js
Labels: fix

#402 feat: add features
  .yarn/versions/60290c43.yml
  packages/popup/src/components/PasswordInput.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/Unlock/index.js
  packages/popup/src/utils/index.js
  packages/ui/components/Input/index.js
Labels: feature

#404 fix: bugs
  .yarn/versions/864a951c.yml
  packages/popup/src/components/GasFee.js
  packages/popup/src/locales/en.js
Labels: fix

#406 fix: db balance update bug
  .yarn/versions/b198f5d9.yml
  packages/db/package.json
  packages/db/src/main/cfxjs/db/queries.cljs
  shadow-cljs.edn
  yarn.lock
Labels: fix

#410 fix: ddata should be string when import hw account
  .yarn/versions/b4c3f02f.yml
  packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
Labels: fix

#407 fix: fix bugs
  .yarn/versions/dd457590.yml
  packages/popup/src/pages/History/components/HistoryItem.js
  packages/popup/src/pages/Home/index.js
Labels: fix

#413 fix: don't set badge
  .yarn/versions/3c7cbf8b.yml
  packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
Labels: fix

#415 feat: add MAX_PENDING_COUNT
  .yarn/versions/8d6be783.yml
  packages/popup/src/constants/index.js
  packages/popup/src/pages/Home/components/PendingQueue.js
  packages/popup/src/pages/Home/index.js
Labels: feature

#418 feat: replace hw icon
  .yarn/versions/6788d3a9.yml
  packages/browser-extension/images/hardware-wallet-icon.svg
  packages/popup/src/locales/en.js
  packages/popup/src/pages/SelectCreateType/index.js
Labels: feature

#416 fix: bugs
  .yarn/versions/1d878bc7.yml
  packages/ledger/conflux.js
  packages/popup/src/pages/ConnectHardwareWallet/components/OpenApp.js
Labels: fix

#420 fix: add missing error instance check
  .yarn/versions/de23a918.yml
  packages/json-rpc-error/index.js
Labels: fix

#423 fix: fix bugs
  .yarn/versions/c373719e.yml
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/index.js
Labels: fix

#426 fix: override dapp gasprice on cfx mainnet
  .yarn/versions/4da0fc93.yml
  packages/rpcs/cfx_sendTransaction/index.js
  packages/rpcs/cfx_sendTransaction/package.json
  yarn.lock
Labels: fix

#425 fix: show dapp icon
  .yarn/versions/cc336f40.yml
  packages/popup/src/pages/Home/components/useAuthorizedAccountIdIcon.js
Labels: fix

#431 feat: use different html for different page
  .gitignore
  .yarn/versions/6ff32b1b.yml
  packages/popup/public/notification.html.mustache
  packages/popup/public/page.html.mustache
  packages/popup/public/popup.html.mustache
  packages/popup/snowpack.config.cjs
  packages/rpcs/wallet_userApprovedAuthRequest/package.json
  packages/rpcs/wallet_userRejectedAuthRequest/package.json
  packages/webextension/popup.js
  scripts/after_prod.js
  scripts/before_all.js
  scripts/snowpack.base.config.js
  yarn.lock
Labels: feature

#432 feat: support fuzzy in query account
  .yarn/versions/fe6adbaa.yml
  packages/db/src/main/cfxjs/db/queries.cljs
Labels: feature

#430 fix: refactor addToken
  .yarn/versions/8a87d8f7.yml
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/Home/components/AddToken.js
  scripts/after_prod.js
Labels: fix

#429 feat: loading
  .yarn/versions/e78b6042.yml
  packages/popup/src/components/Text/index.css
  packages/popup/src/components/Text/index.js
  packages/popup/src/components/TokenItem.js
  packages/popup/src/hooks/useLoading/PageLoading.js
  packages/popup/src/hooks/useLoading/createPageLoading.js
  packages/popup/src/hooks/useLoading/createSpinLoading.js
  packages/popup/src/hooks/useLoading/createTextLoading.js
  packages/popup/src/hooks/useLoading/index.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/Home/components/CurrentAccount.js
  packages/popup/src/pages/Home/components/CurrentNetwork.js
  packages/popup/src/pages/Home/components/HomeTokenList.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/Unlock/index.js
  scripts/tailwind.config.js
Labels: feature

#437 fix: fix bug
  .yarn/versions/9c8e37ea.yml
  packages/popup/src/components/DisplayBalance.js
  packages/popup/src/pages/History/components/HistoryItem.js
  packages/popup/src/pages/History/index.js
Labels: fix

#439 fix: sentry broken in prod
  .github/workflows/debug-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/prod-release.yaml
  .github/workflows/release.yaml
  .yarn/versions/37c6a9b6.yml
  packages/background/src/index.js
  packages/rpcs/wallet_addVault/index.js
  packages/rpcs/wallet_addVault/package.json
  packages/sentry/index.js
  packages/sentry/package.json
  yarn.lock
Labels: fix

#441 fix: support builtin contract
  .yarn/versions/32b0fb27.yml
  packages/base32-address/index.test.js
  packages/rpc-engine/middlewares/validate-rpc-data.js
  packages/rpc-engine/src/error.js
  packages/rpcs/wallet_enrichConfluxTx/index.js
Labels: tests, fix

#444 fix: several bugs
  .yarn/versions/28d7759c.yml
  packages/ledger/conflux.js
Labels: fix

#443 feat: add error page
  .yarn/versions/3ed34216.yml
  packages/popup/src/components/CopyButton.js
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/Error/index.js
  packages/popup/src/pages/Home/components/NetworkList.js
Labels: feature

#447 feat: Increase blur level of Page type Loading in some private scenes
  .yarn/versions/05bee15c.yml
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/hooks/useLoading/createPageLoading.js
  packages/popup/src/hooks/useLoading/createSpinLoading.js
  packages/popup/src/hooks/useLoading/index.css
  packages/popup/src/hooks/useLoading/index.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
Labels: feature

#438 fix: home token list bug in change to empty data
  .yarn/versions/cc74af5d.yml
  packages/popup/src/pages/Home/components/HomeTokenList.js
Labels: fix

#451 fix: handle the reject result when confirm in dapp
  .yarn/versions/b8667534.yml
  packages/popup/src/components/DappFooter.js
  packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
  packages/popup/src/pages/ConfirmTransaction/index.js
Labels: fix

#454 fix: sendtx create uesless authreq
  .github/workflows/debug-release.yaml
  .yarn/versions/9b80a939.yml
  packages/rpcs/cfx_sendTransaction/index.js
Labels: fix

#448 feat: add icon mark in account and network list
  .yarn/versions/bbd7e90e.yml
  packages/browser-extension/images/select.svg
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/CurrentAccountNetworkLabel.js
  packages/popup/src/pages/Home/components/NetworkList.js
  packages/popup/src/pages/Home/components/index.js
Labels: feature

#450 fix: fix bugs
  .yarn/versions/68369b7e.yml
  packages/popup/src/pages/ConnectSite/index.js
  packages/popup/src/pages/Home/components/Setting.js
  packages/ui/components/Checkbox/__snapshots__/index.test.js.snap
  packages/ui/components/Checkbox/index.js
Labels: fix

#453 feat: add features and fixed bug
  .yarn/versions/543acf56.yml
  packages/browser-extension/images/icon-128.png
  packages/browser-extension/images/icon-16.png
  packages/browser-extension/images/icon-19.png
  packages/browser-extension/images/icon-32.png
  packages/browser-extension/images/icon-38.png
  packages/browser-extension/images/icon-512.png
  packages/browser-extension/images/icon-64.png
  packages/hdkey/index.js
  packages/hdkey/index.test.js
  packages/popup/src/App.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/DappSwitchNetwork/index.js
  packages/popup/src/pages/Home/components/AddToken.js
Labels: feature

#452 feat: add Modal animation
  .yarn/versions/5b8f85ce.yml
  packages/popup/src/hooks/index.js
  packages/ui/components/Modal/__snapshots__/index.test.js.snap
  packages/ui/components/Modal/index.js
  packages/ui/components/Modal/modal.css
  packages/ui/components/Modal/useAnimation.js
Labels: feature

#459 feat: bug and features
  .github/release-drafter-pre.yml
  .yarn/versions/f33b6336.yml
  packages/background/package.json
  packages/background/src/index.js
  packages/background/src/init-db.js
  packages/background/src/rpc-engine-opts.js
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/ledger/conflux.js
  packages/ledger/index.js
  packages/popup/src/components/TokenItem.js
  packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
  packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
  packages/rpcs/wallet_handleUnfinishedCFXTx/package.json
  packages/rpcs/wallet_metadataForPopup/README.md
  packages/rpcs/wallet_metadataForPopup/doc.js
  packages/rpcs/wallet_metadataForPopup/index.js
  packages/rpcs/wallet_metadataForPopup/package.json
  packages/rpcs/wallet_setCurrentNetwork/index.js
  packages/rpcs/wallet_setCurrentNetwork/package.json
  yarn.lock
Labels: feature, fix
