Repository Conflux-Chain/helios, pull requests merged in 2021-11, with the labels that each got.

#187 feat: add 777 abis
  .yarn/versions/da2e4c91.yml
  package.json
  packages/contract-abis/777.js
  packages/contract-method-name/cfx-name.js
  packages/contract-method-name/cfx-name.test.js
  packages/contract-method-name/constance.js
  packages/contract-method-name/index.js
  packages/contract-method-name/package.json
  yarn.lock
Labels: tests, feature

#193 fix: bugs
  .yarn/versions/698c5e4f.yml
  packages/background/src/db-schema.js
  packages/background/src/init-db.js
  packages/built-in-network-icons/BSC.svg
  packages/built-in-network-icons/Conflux.svg
  packages/built-in-network-icons/Ethereum.svg
  packages/built-in-network-icons/README.md
  packages/built-in-network-icons/bnb.svg
  packages/built-in-network-icons/cfx.svg
  packages/built-in-network-icons/eth.svg
  packages/built-in-network-icons/package.json
  packages/consts/index.js
  packages/estimate-tx/index.js
  packages/rpcs/wallet_addNetwork/index.js
  packages/rpcs/wallet_exportAccount/index.js
  packages/rpcs/wallet_getAccountGroup/index.js
  packages/rpcs/wallet_getAccountGroup/index.test.js
  yarn.lock
Labels: tests, fix

#195 fix: bn16 support 0x-prefixed hex decimal
  .yarn/versions/6e894fb9.yml
  packages/estimate-tx/index.js
  packages/estimate-tx/package.json
  yarn.lock
Labels: fix

#200 fix: network.icons => network.icon
  .yarn/versions/195eecbf.yml
  package.json
  packages/background/src/db-schema.js
  packages/background/src/init-db.js
  packages/db/src/main/cfxjs/db/core.cljs
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/doc-ui/rpc-parameter/package.json
  packages/doc-ui/useRPC/package.json
  packages/doc-ui/useSpec/package.json
  packages/fetch-rpc/package.json
  packages/popup/package.json
  shadow-cljs.edn
  yarn.lock
Labels: fix

#203 fix: spec, error handling in detectNetworkType
  .yarn/versions/750192eb.yml
  packages/background/package.json
  packages/background/src/index.integration.test.js
  packages/background/src/rpc-engine-opts.js
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/rpc-engine/middlewares/fetch.js
  packages/rpcs/wallet_detectNetworkType/index.js
  packages/rpcs/wallet_unwatchAsset/index.js
  packages/rpcs/wallet_watchAsset/index.js
  packages/spec/src/main/cfxjs/spec/core.cljs
  yarn.lock
Labels: tests, fix

#206 fix: refactor batch balance and batch address
  .yarn/versions/a875f756.yml
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/ConnectSite/index.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/AddToken.js
Labels: fix

#212 feat: token name length to 40
  .yarn/versions/dee04d31.yml
  packages/token-list-schema/index.js
Labels: feature

#213 feat: add approve and transfer in dapp demo
  examples/basic-dapp/index.html
  examples/basic-dapp/index.js
Labels: feature

#219 feat: add cfxGetFeeData, update estiamte-tx
  packages/estimate-tx/index.js
  packages/popup/src/hooks/index.js
Labels: feature

#209 feat: fix home add token and new seed bug
  .yarn/versions/ffb38ea6.yml
  packages/popup/src/constants/index.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/utils/index.js
Labels: feature

#218 fix: bug fixes
  .yarn/plugins/@yarnpkg/plugin-constraints.cjs
  .yarn/plugins/@yarnpkg/plugin-exec.cjs
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.0.1.cjs
  .yarn/releases/yarn-3.1.0.cjs
  .yarn/versions/244cd955.yml
  .yarnrc
  .yarnrc.yml
  package.json
  packages/background/src/index.integration.test.js
  packages/jazz-icon/package.json
  packages/popup/package.json
  packages/rpc-engine/src/error.js
  packages/rpcs/cfx_estimateGasAndCollateral/index.js
  packages/rpcs/cfx_signTransaction/index.js
  yarn.lock
Labels: tests, fix

#221 feat: add personal sign
  .yarn/versions/e45100a4.yml
  packages/popup/src/App.js
  packages/popup/src/components/AccountDisplay.js
  packages/popup/src/components/CopyButton.js
  packages/popup/src/components/CustomTag.js
  packages/popup/src/components/DappFooter.js
  packages/popup/src/components/DappProgressHeader.js
  packages/popup/src/components/DisplayBalance.js
  packages/popup/src/components/HomeTitle.js
  packages/popup/src/components/LanguageNav.js
  packages/popup/src/components/PasswordInput.js
  packages/popup/src/components/QRCodeButton.js
  packages/popup/src/components/TitleNav.js
  packages/popup/src/components/TokenList.js
  packages/popup/src/constants/index.js
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/ConfirmAddSuggestedToken/index.js
  packages/popup/src/pages/ConnectSite/index.js
  packages/popup/src/pages/CreateSeed/BackupSeed.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CreateSeed/components/SeedWord.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/DappAddNetwork/index.js
  packages/popup/src/pages/DappSwitchNetwork/index.js
  packages/popup/src/pages/Home/components/CurrentAccount.js
  packages/popup/src/pages/Home/components/HomeTokenList.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/RequestSignature/components/PlaintextMessage.js
  packages/popup/src/pages/RequestSignature/index.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/Unlock/index.js
  packages/popup/src/pages/ViewData/index.js
  packages/popup/src/stores/index.js
Labels: feature

#223 feat: add global error config and fix bug
  .yarn/versions/d944c495.yml
  packages/popup/package.json
  packages/popup/src/App.js
  packages/popup/src/components/Avatar.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/index.js
  packages/popup/src/pages/Error/index.js
  packages/ui/data-format/package.json
  yarn.lock
Labels: feature

#215 feat: finish send token in wallet
  .yarn/versions/b3de0327.yml
  examples/basic-dapp/index.html
  examples/basic-dapp/index.js
  packages/estimate-tx/index.js
  packages/popup/package.json
  packages/popup/src/App.js
  packages/popup/src/components/DappFooter.js
  packages/popup/src/components/DisplayBalance.js
  packages/popup/src/components/GasFee.js
  packages/popup/src/components/NumberInput.js
  packages/popup/src/components/ProtectedRoute.js
  packages/popup/src/components/SearchToken.js
  packages/popup/src/components/TokenItem.js
  packages/popup/src/components/TokenList.js
  packages/popup/src/constants/index.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/index.css
  packages/popup/src/locales/en.js
  packages/popup/src/pages/ConfirmAddSuggestedToken/index.js
  packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
  packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
  packages/popup/src/pages/ConfirmTransaction/components/TransactionResult.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/EditGasFee/index.js
  packages/popup/src/pages/EditPermission/index.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/SendTransaction/components/CurrentAccountDisplay.js
  packages/popup/src/pages/SendTransaction/components/CurrentNetworkDisplay.js
  packages/popup/src/pages/SendTransaction/components/ToAddressInput.js
  packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
  packages/popup/src/pages/SendTransaction/components/index.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/popup/src/pages/ViewData/index.js
  packages/popup/src/stores/index.js
  packages/popup/src/utils/api.js
  packages/popup/src/utils/index.js
  packages/ui/components/Input/index.js
  packages/ui/components/Radio/radio.css
  packages/ui/data-format/index.js
  packages/webextension/popup.js
  yarn.lock
Labels: feature

#226 feat: provider api compatible with portal
  .github/workflows/publish-npm-package.yaml
  .github/workflows/push-check.yaml
  .gitignore
  .yarn/versions/2ad4f0a6.yml
  package.json
  packages/browser-extension/manifest.json.mustache
  packages/content-script/index.js.mustache
  packages/content-script/index.test.js
  packages/inpage/setup-inpage-provider.js
  packages/inpage/take-over-portal.js
  packages/rpcs/cfx_accounts/index.js
  packages/rpcs/cfx_requestAccounts/index.js
  packages/rpcs/eth_requestAccounts/index.js
  packages/safe-event-emiter/index.js
  packages/ui/provider-api/index.js
  packages/ui/provider-api/index.test.js
  packages/ui/provider-api/package.json
  scripts/build-content-script.js
  scripts/dev.js
  scripts/prod.js
  scripts/tools.el
  yarn.lock
Labels: tests, feature, breaking-change

#229 fix: new provider api
  .yarn/versions/c98b996a.yml
  package.json
  packages/ui/useRPC/index.js
  yarn.lock
Labels: fix

#231 feat: support more rpc methods
  .yarn/versions/0b1db357.yml
  packages/background/package.json
  packages/background/src/rpc-engine-opts.js
  packages/rpc-engine/middlewares/validate-rpc-data.js
  packages/rpcs/cfx_getAccountPendingInfo/README.md
  packages/rpcs/cfx_getAccountPendingInfo/index.js
  packages/rpcs/cfx_getAccountPendingInfo/package.json
  packages/rpcs/cfx_getAccountPendingTransactions/README.md
  packages/rpcs/cfx_getAccountPendingTransactions/index.js
  packages/rpcs/cfx_getAccountPendingTransactions/package.json
  packages/rpcs/cfx_getBlockByBlockNumber/index.js
  packages/rpcs/cfx_getPoSEconomics/README.md
  packages/rpcs/cfx_getPoSEconomics/index.js
  packages/rpcs/cfx_getPoSEconomics/package.json
  packages/rpcs/cfx_getSupplyInfo/README.md
  packages/rpcs/cfx_getSupplyInfo/index.js
  packages/rpcs/cfx_getSupplyInfo/package.json
  packages/rpcs/cfx_openedMethodGroups/README.md
  packages/rpcs/cfx_openedMethodGroups/index.js
  packages/rpcs/cfx_openedMethodGroups/package.json
  packages/rpcs/txpool_nextNonce/README.md
  packages/rpcs/txpool_nextNonce/index.js
  packages/rpcs/txpool_nextNonce/package.json
  packages/spec/src/main/cfxjs/spec/core.cljs
  scripts/tools.el
  yarn.lock
Labels: feature

#233 fix: fix getting account group bugs and refactor request logic
  .yarn/versions/7a7d64cd.yml
  examples/basic-dapp/index.js
  packages/background/src/index.js
  packages/popup/src/components/DappFooter.js
  packages/popup/src/components/HomeNav.js
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/CreateSeed/BackupSeed.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/Unlock/index.js
Labels: fix

#235 fix: estimate-tx and zip release
  .yarn/versions/ef0dc2e2.yml
  package.json
  packages/estimate-tx/index.js
  scripts/create-zip
  scripts/create-zip.cjs
  yarn.lock
Labels: fix

#237 fix: fix bugs
  .yarn/versions/a9074708.yml
  packages/popup/src/components/DappFooter.js
  packages/popup/src/components/GasFee.js
  packages/popup/src/components/NumberInput.js
  packages/popup/src/hooks/index.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/ConfirmTransaction/components/TransactionResult.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
  packages/ui/data-format/index.js
Labels: fix

#239 fix: bugs
  .yarn/versions/ce5f7957.yml
  package.json
  packages/doc-ui/rpc-parameter/index.js
  packages/doc-ui/rpc-parameter/package.json
  packages/doc-ui/useRPC/index.js
  packages/doc-ui/useSpec/index.js
  packages/popup/package.json
  packages/rpcs/cfx_getLogs/index.js
  packages/rpcs/wallet_getAccountAddressByNetwork/index.js
  packages/rpcs/wallet_getBalance/index.js
  packages/rpcs/wallet_requestPermissions/index.js
  packages/rpcs/wallet_setCurrentAccount/index.js
  packages/rpcs/wallet_setCurrentNetwork/index.js
  packages/rpcs/wallet_validatePassword/index.js
  packages/safe-event-emiter/index.js
  packages/spec/src/main/cfxjs/spec/doc.cljs
  packages/ui/provider-api/index.js
  shadow-cljs.edn
  websites/doc/package.json
  yarn.lock
Labels: fix

#241 fix: fix dapp send native token
  .yarn/versions/97908e2f.yml
  packages/popup/src/components/DappFooter.js
  packages/popup/src/components/GasFee.js
  packages/popup/src/pages/ConfirmTransaction/index.js
Labels: fix

#244 fix: refactor contract-method-name test cases
  .yarn/versions/f4679f1d.yml
  packages/contract-method-name/cfx-name.js
  packages/contract-method-name/cfx-name.test.js
  packages/popup/src/pages/RequestSignature/components/PlaintextMessage.js
  packages/popup/src/pages/RequestSignature/index.js
Labels: tests, fix

#247 feat: some bugs and feature
  .yarn/versions/b157d2b5.yml
  packages/popup/src/components/GasFee.js
  packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
  packages/popup/src/pages/ConfirmTransaction/index.js
  packages/popup/src/pages/EditGasFee/index.js
  packages/popup/src/pages/EditPermission/index.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/RequestSignature/index.js
  packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
  packages/popup/src/pages/SendTransaction/index.js
  packages/popup/src/stores/index.js
Labels: feature

#251 fix: warning
  .yarn/versions/7cfddaca.yml
  packages/popup/src/components/NumberInput.js
Labels: fix

#253 fix: fix logic bugs
  .yarn/versions/493b4e73.yml
  packages/popup/src/pages/ConnectSite/index.js
Labels: fix

#255 feat: send tx and tx status track logic
  .github/scripts/assert-fullnode-error-message-check.mjs
  .github/scripts/check-conflux-rust-error-messages
  .github/workflows/check-conflux-fullnode-error-message.yaml
  .gitignore
  .yarn/versions/751305be.yml
  packages/background/package.json
  packages/background/src/db-schema.js
  packages/background/src/index.js
  packages/background/src/init-db.js
  packages/background/src/rpc-engine-opts.js
  packages/cache-rpc/index.js
  packages/conflux-tx-error/README.md
  packages/conflux-tx-error/index.js
  packages/conflux-tx-error/package.json
  packages/db/src/main/cfxjs/db/core.cljs
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/rpc-engine/middlewares/fetch.js
  packages/rpc-epoch-ref/index.js
  packages/rpcs/cfx_getNextNonce/index.js
  packages/rpcs/cfx_getNextUsableNonce/README.md
  packages/rpcs/cfx_getNextUsableNonce/doc.js
  packages/rpcs/cfx_getNextUsableNonce/index.js
  packages/rpcs/cfx_getNextUsableNonce/package.json
  packages/rpcs/cfx_getStatus/index.js
  packages/rpcs/cfx_getTransactionByHash/index.js
  packages/rpcs/cfx_getTransactionReceipt/index.js
  packages/rpcs/cfx_netVersion/index.js
  packages/rpcs/cfx_sendRawTransaction/index.js
  packages/rpcs/cfx_sendTransaction/index.js
  packages/rpcs/cfx_sendTransaction/package.json
  packages/rpcs/cfx_signTransaction/doc.js
  packages/rpcs/cfx_signTransaction/index.js
  packages/rpcs/wallet_getExplorerUrl/README.md
  packages/rpcs/wallet_getExplorerUrl/doc.js
  packages/rpcs/wallet_getExplorerUrl/index.js
  packages/rpcs/wallet_getExplorerUrl/package.json
  packages/rpcs/wallet_handleUnfinishedCFXTx/README.md
  packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
  packages/rpcs/wallet_handleUnfinishedCFXTx/package.json
  packages/rpcs/wallet_handleUnfinishedTxs/README.md
  packages/rpcs/wallet_handleUnfinishedTxs/index.js
  packages/rpcs/wallet_handleUnfinishedTxs/package.json
  packages/signature/1820-txhash.js
  packages/signature/index.js
  packages/signature/index.test.js
  packages/token-list-schema/index.js
  packages/transducers/index.js
  packages/wallet-permission/permissions.js
  packages/webextension/badge.js
  packages/webextension/index.js
  packages/webextension/notification.js
  packages/webextension/notifications.js
  yarn.lock
Labels: tests, feature

#256 fix: add zero account judgement
  .yarn/versions/43f01152.yml
  packages/popup/src/App.js
  packages/popup/src/hooks/useApi.js
Labels: fix

#258 feat: add send token search
  .yarn/versions/abb7389b.yml
  packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
Labels: feature

#261 feat: features and bugs
  .github/scripts/assert-fullnode-error-message-check.mjs
  .yarn/versions/15e0e605.yml
  packages/background/src/index.integration.test.js
  packages/content-script/index.js.mustache
  packages/db/src/main/cfxjs/db/queries.cljs
  packages/extension-runtime/background.js
  packages/inpage/take-over-portal.js
  packages/popup/src/hooks/useApi.js
  packages/rpc-engine/index.js
  packages/rpc-engine/middleware.js
  packages/rpc-engine/middlewares/validate-rpc-data.js
  packages/rpcs/cfx_gasPrice/index.js
  packages/rpcs/cfx_gasPrice/package.json
  packages/rpcs/wallet_addVault/index.js
  packages/rpcs/wallet_getNetwork/index.js
  packages/rpcs/wallet_refetchBalance/index.js
  packages/spec/src/main/cfxjs/spec/cljs.cljs
  packages/spec/src/main/cfxjs/spec/core.cljs
  packages/ui/provider-api/index.js
  yarn.lock
Labels: tests, feature

#263 fix: fix logic bugs
  .yarn/versions/60b64115.yml
  packages/popup/src/components/NetworkContent.js
  packages/popup/src/hooks/useApi.js
  packages/popup/src/pages/Home/components/AddToken.js
Labels: fix
