Repository Conflux-Chain/helios, pull requests merged in 2021-09, with the labels that each got.

#89 ci: assets size check
  .github/workflows/opti-image.yaml
  .github/workflows/publish-npm-package.yaml
Labels: ci

#91 feat: replace useStore with createWithUseRPC
  .yarn/versions/a5c3c74e.yml
  packages/popup/src/App.js
  packages/popup/src/hooks/zustand.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/store/befores.js
  packages/popup/src/store/index.js
  packages/popup/src/store/init-store.js
  packages/popup/src/store/rpc-config.js
  packages/popup/src/store/useStore.js
  packages/ui/useRPC/index.js
  packages/ui/useRPC/setup-provider.js
Labels: feature

#100 feat: refactor current seed page
  .yarn/versions/14587feb.yml
  packages/browser-extension/images/create-seed-bg.svg
  packages/popup/src/hooks/zustand.js
  packages/popup/src/i18n.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CreateSeed/components/SeedWord.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/store/index.js
  packages/popup/src/stores/index.js
  packages/popup/src/utils/index.js
  packages/ui/icons/Question.js
  packages/ui/icons/index.js
  scripts/snowpack.base.config.js
Labels: feature

#104 feat: new seed phrase
  .yarn/versions/f59aef89.yml
  packages/popup/src/components/CompWithLabel.js
  packages/popup/src/index.css
  packages/popup/src/locales/en.js
  packages/popup/src/pages/CreateSeed/BackupSeed.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CreateSeed/components/SeedWord.js
  packages/popup/src/pages/CreateSeed/components/index.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/stores/index.js
  packages/popup/src/utils/index.js
  packages/ui/icons/Close.js
  packages/ui/icons/index.js
  scripts/tailwind.config.js
Labels: feature

#106 feat: Login register merge
  packages/popup/src/App.js
  packages/popup/src/components/CompWithLabel.js
  packages/popup/src/components/HomeTitle.js
  packages/popup/src/components/LanguageNav.js
  packages/popup/src/components/PasswordInput.js
  packages/popup/src/components/ProtectedRoute.js
  packages/popup/src/components/TextNav.js
  packages/popup/src/components/TitleNav.js
  packages/popup/src/components/index.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/CreateSeed/BackupSeed.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/SelectCreateType/components/CreateTypeItem.js
  packages/popup/src/pages/SelectCreateType/components/index.js
  packages/popup/src/pages/SelectCreateType/index.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/SetPassword/components/index.js
  packages/popup/src/pages/SetPassword/index.js
  packages/popup/src/pages/Welcome/index.js
  packages/popup/src/utils/index.js
  packages/ui/components/Input/index.js
  packages/ui/icons/ArrowDown.js
  packages/ui/icons/ArrowDownFilling.js
  packages/ui/icons/ArrowLeft.js
  packages/ui/icons/ArrowUpFilling.js
  packages/ui/icons/DirectionLeft.js
  packages/ui/icons/LeftArrow.js
  packages/ui/icons/index.js
  scripts/tailwind.config.js
Labels: feature

#103 feat: add some functionality to the accounts module
  .yarn/versions/b570d313.yml
  packages/browser-extension/assets/images/logo.png
  packages/browser-extension/images/existing-seed-phrase-icon.svg
  packages/browser-extension/images/new-seed-phrase-icon.svg
  packages/browser-extension/images/private-key-icon.svg
  packages/browser-extension/images/seed-phrase-icon.svg
  packages/popup/package.json
  packages/popup/src/App.js
  packages/popup/src/components/CompWithLabel.js
  packages/popup/src/components/HomeTitle.js
  packages/popup/src/components/LanguageNav.js
  packages/popup/src/components/PasswordInput.js
  packages/popup/src/components/ProtectedRoute.js
  packages/popup/src/components/TitleNav.js
  packages/popup/src/components/index.js
  packages/popup/src/constants.js
  packages/popup/src/constants/index.js
  packages/popup/src/constants/rpcDeps.js
  packages/popup/src/hooks/index.js
  packages/popup/src/index.css
  packages/popup/src/locales/en.js
  packages/popup/src/locales/zh.js
  packages/popup/src/pages/CreateAccount/components/index.js
  packages/popup/src/pages/CreateAccount/index.js
  packages/popup/src/pages/CreateSeed/BackupSeed.js
  packages/popup/src/pages/CreateSeed/ConfirmSeed.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/Error/index.js
  packages/popup/src/pages/Home/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/SelectCreateType/components/CreateTypeItem.js
  packages/popup/src/pages/SelectCreateType/components/index.js
  packages/popup/src/pages/SelectCreateType/index.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/SetPassword/components/index.js
  packages/popup/src/pages/SetPassword/index.js
  packages/popup/src/pages/Unlock/index.js
  packages/popup/src/pages/Welcome/index.js
  packages/popup/src/stores/index.js
  packages/popup/src/utils/index.js
  packages/ui/components/Dropdown/index.js
  packages/ui/components/Input/index.js
  packages/ui/icons/ArrowDownFilling.js
  packages/ui/icons/ArrowLeft.js
  packages/ui/icons/ArrowUpFilling.js
  packages/ui/icons/DirectionLeft.js
  packages/ui/icons/LeftTriangle.js
  packages/ui/icons/index.js
  scripts/tailwind.config.js
  yarn.lock
Labels: feature

#108 ci: update prev comment instead of creating a new one
  .github/scripts/commentPRDebugRelease.js
Labels: ci

#114 feat: add missing rpcs in pref dapp interaction pr
  .yarn/versions/52197918.yml
  packages/background/package.json
  packages/background/src/index.integration.test.js
  packages/background/src/rpc-engine-opts.js
  packages/rpcs/wallet_deleteApp/README.md
  packages/rpcs/wallet_deleteApp/index.js
  packages/rpcs/wallet_deleteApp/package.json
  packages/rpcs/wallet_getCurrentViewingApp/README.md
  packages/rpcs/wallet_getCurrentViewingApp/index.js
  packages/rpcs/wallet_getCurrentViewingApp/package.json
  packages/rpcs/wallet_getNetwork/README.md
  packages/rpcs/wallet_getNetwork/index.js
  packages/rpcs/wallet_getNetwork/package.json
  packages/webextension/index.js
  packages/webextension/tab.js
  yarn.lock
Labels: tests, feature

#116 fix: broken doc build
  .yarn/versions/95459a52.yml
  packages/browser-extension/manifest.json.mustache
  packages/rpc-engine/middlewares/validate-rpc-data.js
  packages/rpcs/wallet_addVault/index.js
  packages/rpcs/wallet_getCurrentViewingApp/index.js
  packages/rpcs/wallet_importAddress/index.js
  packages/rpcs/wallet_importMnemonic/index.js
  packages/rpcs/wallet_importPrivateKey/index.js
Labels: fix

#118 ci: faster npm publish workflow
  .github/workflows/publish-npm-package.yaml
  packages/fectch-rpc-middleware/README.md
  packages/fectch-rpc-middleware/index.js
  packages/fectch-rpc-middleware/package.json
  yarn.lock
Labels: ci

#121 fix: isLocked return false if has no group
  .yarn/versions/4100ae07.yml
  packages/background/package.json
  packages/background/src/rpc-engine-opts.js
  packages/popup/src/App.js
  packages/popup/src/components/ProtectedRoute.js
  packages/popup/src/constants/rpcDeps.js
  packages/popup/src/pages/Error/index.js
  packages/popup/src/stores/index.js
  packages/rpc-engine/middlewares/validate-rpc-data.js
  packages/rpcs/wallet_isLocked/index.js
  packages/rpcs/wallet_zeroAccountGroup/README.md
  packages/rpcs/wallet_zeroAccountGroup/index.js
  packages/rpcs/wallet_zeroAccountGroup/package.json
  yarn.lock
Labels: fix

#124 feat: add estimate rpc, upgrade packages
  .yarn/versions/de728ebd.yml
  packages/associative/package.json
  packages/background/package.json
  packages/background/src/index.integration.test.js
  packages/background/src/index.js
  packages/background/src/rpc-engine-opts.js
  packages/cache-rpc/package.json
  packages/compose/package.json
  packages/content-script/package.json
  packages/csp/package.json
  packages/eth-transaction-schema/README.md
  packages/eth-transaction-schema/index.js
  packages/eth-transaction-schema/package.json
  packages/extension-runtime/package.json
  packages/fetch-rpc/package.json
  packages/inpage/package.json
  packages/iterators/package.json
  packages/rpc-engine/package.json
  packages/rpcs/cfx_estimateGasAndCollateral/README.md
  packages/rpcs/cfx_estimateGasAndCollateral/index.js
  packages/rpcs/cfx_estimateGasAndCollateral/package.json
  packages/rpcs/eth_estimateGas/README.md
  packages/rpcs/eth_estimateGas/index.js
  packages/rpcs/eth_estimateGas/package.json
  packages/rpcs/wallet_getAccountAddressByNetwork/README.md
  packages/rpcs/wallet_getAccountAddressByNetwork/index.js
  packages/rpcs/wallet_getAccountAddressByNetwork/package.json
  packages/safe-event-emiter/package.json
  packages/spec/index.js
  packages/transducers/package.json
  yarn.lock
Labels: tests, feature

#123 chore: optimize prod build
  .yarn/versions/bd68dd54.yml
  packages/background/snowpack.config.cjs
  scripts/prod.js
  scripts/snowpack.base.config.js
Labels: enhancement

#126 feat: allow grant app permissions directly from popup
  .yarn/versions/728044eb.yml
  packages/addr-by-network/index.js
  packages/addr-by-network/index.test.js
  packages/background/src/db-schema.js
  packages/background/src/index.integration.test.js
  packages/background/src/index.js
  packages/background/src/init-db.js
  packages/checks/package.json
  packages/db/src/main/cfxjs/db/core.cljs
  packages/doc-ui/rpc-parameter/index.js
  packages/doc-ui/useRPC/index.js
  packages/rpcs/cfx_signTypedData_v4/index.js
  packages/rpcs/eth_estimateGas/package.json
  packages/rpcs/personal_sign/index.js
  packages/rpcs/personal_sign/package.json
  packages/rpcs/wallet_addVault/index.js
  packages/rpcs/wallet_createAccount/index.js
  packages/rpcs/wallet_createAddress/index.js
  packages/rpcs/wallet_exportAccountGroup/index.js
  packages/rpcs/wallet_generatePrivateKey/package.json
  packages/rpcs/wallet_getAccountAddressByNetwork/index.js
  packages/rpcs/wallet_getBalance/index.test.js
  packages/rpcs/wallet_getNextNonce/index.test.js
  packages/rpcs/wallet_requestPermissions/index.js
  packages/rpcs/wallet_setCurrentAccount/index.js
  packages/spec/src/main/cfxjs/spec/doc.cljs
  packages/test-helpers/index.js
  packages/workspace-tools/rpc/get-all.js
  yarn.lock
Labels: tests, feature

#129 fix: unlock wallet after creating vault
  .yarn/versions/6f2a1189.yml
  packages/popup/src/App.js
  packages/rpcs/wallet_addVault/index.js
  packages/rpcs/wallet_getCurrentViewingApp/index.js
  packages/webextension/tab.js
Labels: fix

#133 fix: spec and rpc doc
  .yarn/versions/6f2a1189.yml
  packages/doc-ui/rpc-parameter/index.js
  packages/doc-ui/useRPC/index.js
  packages/doc-ui/useSpec/index.js
  packages/docusaurus-plugin/index.js
  packages/index.html
  packages/rpcs/cfx_chainId/index.js
  packages/rpcs/cfx_netVersion/index.js
  packages/rpcs/cfx_requestAccounts/index.js
  packages/rpcs/eth_requestAccounts/index.js
  packages/rpcs/wallet_generatePrivateKey/index.js
  packages/rpcs/wallet_getCurrentAccount/index.js
  packages/rpcs/wallet_getCurrentNetwork/index.js
  packages/rpcs/wallet_getCurrentViewingApp/index.js
  packages/rpcs/wallet_getPendingAuthRequest/index.js
  packages/rpcs/wallet_getPermissions/index.js
  packages/rpcs/wallet_requestUnlockUI/index.js
  packages/rpcs/wallet_setCurrentNetwork/index.js
  packages/rpcs/wallet_zeroAccountGroup/index.js
  packages/spec/src/main/cfxjs/spec/core.cljs
  packages/spec/src/main/cfxjs/spec/doc.cljs
  packages/spec/src/main/cfxjs/spec/gen.cljs
  shadow-cljs.edn
  websites/doc/babel.config.js
  websites/doc/package.json
  yarn.lock
Labels: fix

#134 feat: add auth and disconnect action
  .yarn/versions/612d17e9.yml
  packages/browser-extension/images/home-bg.svg
  packages/popup/src/components/HomeNav.js
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/pages/Home/components/CurrentDapp.js
  packages/popup/src/pages/Home/index.js
  scripts/before_all.js
Labels: feature

#136 feat: add AccountList and NetworkList
  .yarn/versions/e736dd42.yml
  packages/background/src/init-db.js
  packages/popup/src/App.js
  packages/popup/src/components/ProtectedRoute.js
  packages/popup/src/components/SlideCard.js
  packages/popup/src/components/index.js
  packages/popup/src/constants/index.js
  packages/popup/src/constants/route.js
  packages/popup/src/constants/rpcMethods.js
  packages/popup/src/hooks/index.js
  packages/popup/src/index.css
  packages/popup/src/index.js
  packages/popup/src/locales/en.js
  packages/popup/src/locales/zh.js
  packages/popup/src/pages/CreateSeed/BackupSeed.js
  packages/popup/src/pages/CreateSeed/NewSeed.js
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/CurrentAccount.js
  packages/popup/src/pages/Home/components/CurrentAccountNetworkLabel.js
  packages/popup/src/pages/Home/components/CurrentNetwork.js
  packages/popup/src/pages/Home/components/NetworkList.js
  packages/popup/src/pages/Home/components/index.js
  packages/popup/src/pages/Home/components/useAuthorizedAccountIdIcon.js
  packages/popup/src/pages/Home/index.js
  packages/popup/src/pages/ImportPrivateKey/index.js
  packages/popup/src/pages/ImportSeedPhrase/index.js
  packages/popup/src/pages/SelectCreateType/index.js
  packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
  packages/popup/src/pages/Unlock/index.js
  packages/popup/src/pages/Welcome/index.js
  packages/popup/src/utils/index.js
  scripts/tailwind.config.js
Labels: feature

#139 feat: Add token
  .yarn/versions/34918779.yml
  packages/popup/src/components/SlideCard.js
  packages/popup/src/locales/en.js
  packages/popup/src/pages/Home/components/AccountList.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/Home/components/CurrentAccount.js
  packages/popup/src/pages/Home/components/CurrentNetwork.js
  packages/popup/src/pages/Home/components/NetworkList.js
  packages/popup/src/pages/Home/components/TokenItem.js
  packages/popup/src/pages/Home/components/TokenList.js
  packages/popup/src/pages/Home/components/index.js
  packages/popup/src/pages/Home/index.js
  packages/ui/components/Input/__snapshots__/index.test.js.snap
  packages/ui/components/Input/index.js
  packages/ui/components/Input/index.test.js
  packages/ui/icons/CloseCircleFilled.js
  packages/ui/icons/SearchOutlined.js
  packages/ui/icons/SelectedOutlined.js
  packages/ui/icons/index.js
Labels: tests, feature

#141 feat: refactor towtone icons
  .yarn/versions/67b43864.yml
  packages/popup/src/pages/CurrentSeed/index.js
  packages/popup/src/pages/Home/components/AddToken.js
  packages/popup/src/pages/Home/components/TokenItem.js
  packages/ui/components/Alert/__snapshots__/index.test.js.snap
  packages/ui/components/Alert/index.js
  packages/ui/components/Checkbox/__snapshots__/index.test.js.snap
  packages/ui/components/Checkbox/index.js
  packages/ui/components/Menu/MenuItem.js
  packages/ui/components/Menu/__snapshots__/MenuItem.test.js.snap
  packages/ui/components/Message/index.js
  packages/ui/components/Notification/index.js
  packages/ui/icons/CheckCircleFilled.js
  packages/ui/icons/CheckSquareFilled.js
  packages/ui/icons/CheckSquareOutlined.js
  packages/ui/icons/ExclamationCircleFilled.js
  packages/ui/icons/InfoCircleFilled.js
  packages/ui/icons/SelectedTowTone.js
  packages/ui/icons/index.js
Labels: feature
